name: myapp
description: "A new Flutter project."

# Evita que este paquete se publique accidentalmente en pub.dev
publish_to: 'none'

# Versión del proyecto: major.minor.patch+build
version: 1.0.0+1

# Define la versión mínima del SDK de Dart que tu proyecto soporta
environment:
  sdk: ^3.7.0

# Dependencias principales del proyecto
dependencies:
  flutter:
    sdk: flutter

  # Opción 1: usar la versión de GitHub del paquete qr_code_scanner
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
      ref: master

  # Opción 2 (comentada): si prefieres usar la versión publicada en pub.dev, usa esta línea en su lugar
  # qr_code_scanner: ^1.0.0

  # Paquete para hacer peticiones HTTP
  http: ^0.13.6

  # Para guardar datos localmente en el dispositivo
  shared_preferences: ^2.2.2

  # Íconos al estilo iOS
  cupertino_icons: ^1.0.8

# Dependencias de desarrollo (para pruebas, análisis de código, etc.)
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Conjunto de reglas de buenas prácticas recomendadas para Flutter
  flutter_lints: ^5.0.0

# Configuraciones específicas de Flutter
flutter:
  # Incluye la fuente de íconos de Material Design
  uses-material-design: true

  # Aquí puedes agregar assets (como imágenes) si los necesitas:
  # assets:
  #   - assets/images/logo.png

  # Aquí puedes agregar fuentes personalizadas:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
